name: Build and release

on:

  pull_request:
    branches: [ "develop" ]

jobs:
  build_artifact:
    matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ["8.8.4"]
        cabal: ["3.2"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup GHC and cabal-install
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          
      - name: Freeze
        run: |
          cabal freeze
    
      - name: Cache ~/.cabal/store
        uses: actions/cache@v3.2.3
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build binary
        run: |
          mkdir dist
          cabal install exe:fixpoint --install-method=copy --overwrite-policy=always --installdir=dist --enable-split-sections
      
      - if: matrix.os == 'windows-latest'
        name: Set extension to .exe on Windows
        run: echo "::set-env name=EXT::.exe"

      - name: Set binary path name
        run: echo "::set-env name=BINARY_PATH::./dist/stan${{ env.EXT }}"

      - name: Compress binary
        uses: svenstaro/upx-action@2.0.1
        with:
          file: ${{ env.BINARY_PATH }}
